### ISSUE TITLE
Decide if we should move from using raster to terra

### ISSUE THREAD

**Issue by Nowosad** [Nowosad/raceland#9]
https://github.com/Nowosad/raceland/tree/terra

**Comment by Nowosad** [comment]
Vignettes cleaning + improved raster support is still needed.

**Comment by Nowosad** [comment]
Vignettes are cleaned

**Comment by rsbivand** [comment]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

Again, I think that this is in hand, but not yet completed for this package. Is the **rgdal** import ready to be replaced by **terra**? I do see in revdep checks:
```
* checking dependencies in R code ... NOTE
Namespaces in Imports field not imported from:
  ‘comat’ ‘rgdal’
  All declared Imports should be used.
```

**Comment by rsbivand** [comment]
This package has strong dependence on at least one of `rgdal`, `rgeos` or `maptools`, but does not seem to use any functionality in code. The usage may have been in `raster`, which now uses `terra` instead, or may be in examples or vignettes. Please move all use of `rgdal`, `rgeos` or `maptools` to Suggests: and protect any use against these packages not being present. The packages will be archived in October 2023. See https://r-spatial.org/r/2022/12/14/evolution2.html and https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1.

**Comment by Nowosad** [comment]
Thank you @rsbivand -- a new version (without rgdal) is now on CRAN -- https://cran.r-project.org/package=raceland.

**Comment by rsbivand** [comment]
Confirmed CMD check in a scenario using sp evolution status 2 (substitute use of rgdal with sf for projection/transformation/CRS) and absence of retiring packages from the library path:
[00check.log](https://github.com/Nowosad/raceland/files/11352399/00check.log)
